version: '3.8'

services:
  server:
    build:
      context: ./server
    ports:
      - "8080:8080"
    restart: unless-stopped

  client:
    build:
      context: ./client
    ports:
      - "3000:80"
    depends_on:
      - server
    restart: unless-stopped
